# -*- coding: utf-8 -*-
"""Proyecto final generador.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wFKKcb2YrKScuVNAlIEfFHx2ZtoIxAVq
"""

import random

# Estructuras de datos
clases_disponibles = {
    'Quimica': {'Duracion': 2},
    'Matematicas': {'Duracion': 2},
    'Historia': {'Duracion': 2},
    # Agrega más clases según sea necesario
}

salones = {f'X{i}': {} for i in range(1, 23)}

profesores = {}

# Función para generar horarios aleatorios
def generar_horarios():
    for salon in salones:
        for dia in ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes']:
            horario = generar_horario(dia)
            salones[salon][dia] = horario

# Función para generar horario para un día específico
def generar_horario(dia):
    horario = []
    horas_disponibles = list(range(9, 17, 2))  # Horas disponibles de 9:00 AM a 5:00 PM

    while horas_disponibles:
        clase = random.choice(list(clases_disponibles.keys()))
        duracion = clases_disponibles[clase]['Duracion']
        horario_clase = []

        for _ in range(duracion):
            hora = random.choice(horas_disponibles)
            horario_clase.append((hora, hora + 2))
            horas_disponibles.remove(hora)

        horario.append({'Clase': clase, 'Horario': horario_clase})

    return horario

# Función para añadir profesor a un salon y materia
def añadir_profesor():
    salon = input("Ingrese el nombre del salón: ")
    materia = input("Ingrese el nombre de la materia: ")
    profesor = input("Ingrese el nombre del profesor: ")

    if salon in salones and materia in clases_disponibles:
        salones[salon][materia]['Profesor'] = profesor
        print(f"Profesor {profesor} asignado a {materia} en {salon}.")
    else:
        print("Error: Salón o materia no encontrados.")

# Función para mostrar horarios
def mostrar_horarios():
    for salon, horarios in salones.items():
        print(f"\nSalón: {salon}")
        for dia, horario in horarios.items():
            print(f"\n{dia}:")
            for clase in horario:
                print(f"  {clase['Clase']} - {clase['Horario']}")

# Función para mostrar el horario de un salón específico
def mostrar_horario_salon():
    salon = input("Ingrese el nombre del salón: ")
    if salon in salones:
        print(f"\nHorario del Salón {salon}:")
        for dia, horario in salones[salon].items():
            print(f"\n{dia}:")
            for clase in horario:
                print(f"  {clase['Clase']} - {clase['Horario']}")
    else:
        print("Error: Salón no encontrado.")

# Menú principal
while True:
    print("\n--- Menú ---")
    print("1. Generar Horarios")
    print("2. Añadir Profesor")
    print("3. Mostrar Horarios")
    print("4. Mostrar Horario de un Salón")
    print("5. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == '1':
        generar_horarios()
        print("Horarios generados exitosamente.")
    elif opcion == '2':
        añadir_profesor()
    elif opcion == '3':
        mostrar_horarios()