from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 771, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 741, 15))
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(-10, 10, 761, 60))
        self.label_2.setMinimumSize(QtCore.QSize(0, 60))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Gumbo")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 741, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 100, 751, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 120, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(0, 20, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(0, 50, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(0, 70, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(0, 90, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(0, 110, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.frame_3)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(0, 10, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(0, 40, 741, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(0, 80, 741, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(0, 100, 741, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(0, 10, 761, 60))
        self.label_16.setMinimumSize(QtCore.QSize(0, 60))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Gumbo")
        font.setPointSize(26)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(0, 10, 741, 15))
        self.label_17.setMinimumSize(QtCore.QSize(0, 15))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(0, 90, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(0, 60, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setUnderline(True)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setGeometry(QtCore.QRect(0, 110, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        self.label_37.setGeometry(QtCore.QRect(0, 150, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setGeometry(QtCore.QRect(0, 470, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        self.label_39.setGeometry(QtCore.QRect(0, 170, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_3)
        self.label_40.setGeometry(QtCore.QRect(0, 210, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        self.label_41.setGeometry(QtCore.QRect(0, 250, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(0, 270, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        self.label_43.setGeometry(QtCore.QRect(0, 320, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(0, 370, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_3)
        self.label_45.setGeometry(QtCore.QRect(0, 390, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(0, 10, 741, 15))
        self.label_18.setMinimumSize(QtCore.QSize(0, 15))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(0, 10, 761, 60))
        self.label_19.setMinimumSize(QtCore.QSize(0, 60))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Gumbo")
        font.setPointSize(26)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_46 = QtWidgets.QLabel(self.tab_4)
        self.label_46.setGeometry(QtCore.QRect(0, 60, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setUnderline(True)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_48 = QtWidgets.QLabel(self.tab_4)
        self.label_48.setGeometry(QtCore.QRect(0, 90, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_4)
        self.label_49.setGeometry(QtCore.QRect(0, 120, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_4)
        self.label_50.setGeometry(QtCore.QRect(0, 160, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_4)
        self.label_51.setGeometry(QtCore.QRect(0, 180, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_4)
        self.label_52.setGeometry(QtCore.QRect(0, 210, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_4)
        self.label_53.setGeometry(QtCore.QRect(0, 230, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_4)
        self.label_54.setGeometry(QtCore.QRect(0, 260, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_4)
        self.label_55.setGeometry(QtCore.QRect(0, 300, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_4)
        self.label_56.setGeometry(QtCore.QRect(0, 320, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_4)
        self.label_57.setGeometry(QtCore.QRect(0, 350, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.tab_4)
        self.label_58.setGeometry(QtCore.QRect(0, 370, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_4)
        self.label_59.setGeometry(QtCore.QRect(0, 390, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_4)
        self.label_60.setGeometry(QtCore.QRect(0, 430, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(0, 10, 741, 15))
        self.label_20.setMinimumSize(QtCore.QSize(0, 15))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(0, 10, 761, 60))
        self.label_21.setMinimumSize(QtCore.QSize(0, 60))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Gumbo")
        font.setPointSize(26)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_61 = QtWidgets.QLabel(self.tab_2)
        self.label_61.setGeometry(QtCore.QRect(0, 60, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_2)
        self.label_62.setGeometry(QtCore.QRect(0, 80, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        self.label_63.setGeometry(QtCore.QRect(0, 490, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.tab_2)
        self.label_64.setGeometry(QtCore.QRect(0, 120, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.tab_2)
        self.label_65.setGeometry(QtCore.QRect(0, 160, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_2)
        self.label_66.setGeometry(QtCore.QRect(0, 470, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.tab_2)
        self.label_67.setGeometry(QtCore.QRect(0, 180, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.tab_2)
        self.label_68.setGeometry(QtCore.QRect(0, 230, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.tab_2)
        self.label_69.setGeometry(QtCore.QRect(0, 250, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.tab_2)
        self.label_70.setGeometry(QtCore.QRect(0, 300, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.tab_2)
        self.label_71.setGeometry(QtCore.QRect(0, 320, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.tab_2)
        self.label_72.setGeometry(QtCore.QRect(0, 340, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(0, 10, 741, 15))
        self.label_22.setMinimumSize(QtCore.QSize(0, 15))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(0, 10, 761, 60))
        self.label_23.setMinimumSize(QtCore.QSize(0, 60))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Gumbo")
        font.setPointSize(26)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_47 = QtWidgets.QLabel(self.tab_5)
        self.label_47.setGeometry(QtCore.QRect(0, 60, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_73 = QtWidgets.QLabel(self.tab_5)
        self.label_73.setGeometry(QtCore.QRect(0, 90, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_73.setFont(font)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_5)
        self.label_74.setGeometry(QtCore.QRect(0, 110, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_74.setFont(font)
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.tab_5)
        self.label_75.setGeometry(QtCore.QRect(0, 140, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.tab_5)
        self.label_76.setGeometry(QtCore.QRect(0, 160, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_76.setFont(font)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.tab_5)
        self.label_77.setGeometry(QtCore.QRect(0, 190, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.tab_5)
        self.label_78.setGeometry(QtCore.QRect(0, 210, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_78.setFont(font)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.tab_5)
        self.label_79.setGeometry(QtCore.QRect(0, 240, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.tab_5)
        self.label_80.setGeometry(QtCore.QRect(0, 260, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_80.setFont(font)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.tab_5)
        self.label_81.setGeometry(QtCore.QRect(0, 280, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_81.setFont(font)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.tab_5)
        self.label_82.setGeometry(QtCore.QRect(0, 310, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.tab_5)
        self.label_83.setGeometry(QtCore.QRect(0, 330, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_83.setFont(font)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.tab_5)
        self.label_84.setGeometry(QtCore.QRect(0, 350, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_84.setFont(font)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.tab_5)
        self.label_85.setGeometry(QtCore.QRect(0, 380, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.tab_5)
        self.label_86.setGeometry(QtCore.QRect(-10, 400, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_86.setFont(font)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.tab_5)
        self.label_87.setGeometry(QtCore.QRect(0, 420, 761, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_87.setFont(font)
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.tab_5)
        self.label_88.setGeometry(QtCore.QRect(0, 450, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_88.setFont(font)
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.tab_5)
        self.label_89.setGeometry(QtCore.QRect(260, 450, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_89.setFont(font)
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.tab_5)
        self.label_90.setGeometry(QtCore.QRect(510, 450, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_90.setFont(font)
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.tab_5)
        self.label_91.setGeometry(QtCore.QRect(0, 470, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.tab_5)
        self.label_92.setGeometry(QtCore.QRect(0, 490, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        font.setUnderline(False)
        self.label_92.setFont(font)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.tab_5)
        self.label_93.setGeometry(QtCore.QRect(520, 470, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_93.setFont(font)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.tab_5)
        self.label_94.setGeometry(QtCore.QRect(250, 470, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_94.setFont(font)
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.tab_5)
        self.label_95.setGeometry(QtCore.QRect(250, 490, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_95.setFont(font)
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.line = QtWidgets.QFrame(self.tab_5)
        self.line.setGeometry(QtCore.QRect(510, 450, 20, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_5)
        self.line_2.setGeometry(QtCore.QRect(250, 450, 3, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(0, 60, 761, 60))
        self.label_25.setMinimumSize(QtCore.QSize(0, 60))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Gumbo")
        font.setPointSize(26)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setGeometry(QtCore.QRect(0, 430, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Gumbo")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(0, 160, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(0, 230, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(0, 300, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(0, 370, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setGeometry(QtCore.QRect(0, 140, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(0, 210, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setGeometry(QtCore.QRect(0, 280, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(0, 350, 761, 20))
        font = QtGui.QFont()
        font.setFamily("Nunito Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.line_4 = QtWidgets.QFrame(self.tab_6)
        self.line_4.setGeometry(QtCore.QRect(207, 110, 341, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.tab_6)
        self.line_5.setGeometry(QtCore.QRect(210, 400, 341, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ayuda"))
        self.label.setText(_translate("MainWindow", "Se bienvenido a"))
        self.label_2.setText(_translate("MainWindow", "GENERADOR DE HORARIOS"))
        self.label_3.setText(_translate("MainWindow", "Creado por el equipo de desarrollo los BichoLovers"))
        self.label_4.setText(_translate("MainWindow", "Este programa está diseñado para facilitar el trabajo del administrador del edificio X de este centro Universitario"))
        self.label_6.setText(_translate("MainWindow", "Este solo tiene que realizar un archivo CSV en el que plasme lo siguiente:"))
        self.label_5.setText(_translate("MainWindow", "Primer Columna: Nombre de la Materia"))
        self.label_7.setText(_translate("MainWindow", "Segunda Columna: Cantidad de Horas semanales"))
        self.label_8.setText(_translate("MainWindow", "EJEMPLO"))
        self.label_9.setText(_translate("MainWindow", "Logica Matematica,4"))
        self.label_10.setText(_translate("MainWindow", "Precalculo,4"))
        self.label_11.setText(_translate("MainWindow", "Introduccion a la ingenieria,4"))
        self.label_12.setText(_translate("MainWindow", "Una vez generado tu archivo \"generador.csv\" ( o el nombre que tu desees ponerle), ya tendrás todo lo necesario para utilizar esta sencilla aplicación!"))
        self.label_13.setText(_translate("MainWindow", "Como pudiste observar, el menu principal se compone de 4 botones principales, y el botón de \"Ayuda\" que acabas de presionar para abrir esta ventana."))
        self.label_14.setText(_translate("MainWindow", "En las siguientes pestañas, te explicaremos con lujo de detalle, la manera de usar cada una de las funciones principales de esta aplicación,"))
        self.label_15.setText(_translate("MainWindow", "así que cada que tengas alguna duda, puedes revisar este pequeño manual de usuario anexado en el menu principal para tu comodidad."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Bienvenida"))
        self.label_16.setText(_translate("MainWindow", "GENERAR HORARIOS"))
        self.label_17.setText(_translate("MainWindow", "Función"))
        self.label_26.setText(_translate("MainWindow", "Como se indica en la pestaña de bienvenida, es necesario el crear un archivo .CSV, para poder hacer uso de esta ventana,"))
        self.label_35.setText(_translate("MainWindow", "NOTA // LE RECOMENDAMOS LEER LA PESTAÑA \"BIENVENIDA\" EN DADO CASO DE NO SABER EL FORMATO INTERNO DEL ARCHIVO CSV"))
        self.label_36.setText(_translate("MainWindow", "una vez tengas tu archivo generador creado, lo puedes almacenar en cualquier directorio de tu computador."))
        self.label_37.setText(_translate("MainWindow", "Al abrir la ventana Generar horarios, te vas a topar con dos botones y un espacio en blanco"))
        self.label_38.setText(_translate("MainWindow", "ERROR: Si haces click en el botón \"Generar horarios\" sin haber importado ningún archivo, saltará un mensaje de error"))
        self.label_39.setText(_translate("MainWindow", "lo primero que debes hacer, es hacer click en el botón \"Buscar archivo\"."))
        self.label_40.setText(_translate("MainWindow", "Estó abrirá el explorador de archivos de Windows, en donde únicamente te dejará seleccionar un archivo de formato CSV"))
        self.label_41.setText(_translate("MainWindow", "Una vez seleccionado el documento, dentro del espacio en blanco abajo del botón,"))
        self.label_42.setText(_translate("MainWindow", "aparecerá la ruta del documento seleccionado, para que puedas verificar que sea la correcta"))
        self.label_43.setText(_translate("MainWindow", "Por último, solo tienes que hacer click en el botón \"Generar Horarios\""))
        self.label_44.setText(_translate("MainWindow", "Te tiene que aparecer un mensaje en donde te indique que se han generado con éxito"))
        self.label_45.setText(_translate("MainWindow", "En dado caso que no sea así, favor de verificar que la sintaxis de tu archivo CSV sea correcta."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Generar Horarios"))
        self.label_18.setText(_translate("MainWindow", "Función"))
        self.label_19.setText(_translate("MainWindow", "CONSULTAR HORARIO"))
        self.label_46.setText(_translate("MainWindow", "NOTA // LE RECOMENDAMOS LEER LA PESTAÑA \"GENERAR HORARIOS\" EN DADO CASO DE NO TENER NINGÚN HORARIO DESPLIEGADO EN ESTA FUNCIÓN"))
        self.label_48.setText(_translate("MainWindow", "Una vez generados los horarios, es hora de consultarlos!"))
        self.label_49.setText(_translate("MainWindow", "Cuando hagas click en está función dentro del menu principal, se te despliegará una ventana que internamente tiene dos pestañas:"))
        self.label_50.setText(_translate("MainWindow", "Horario General"))
        self.label_51.setText(_translate("MainWindow", "En esta pestaña, se despliegará en forma de tabla, el horario de absolutamente todas las Aulas del edificio X sin excepciones."))
        self.label_52.setText(_translate("MainWindow", "En la primer columna aparece el aula (X1, X2, X3, X4, ... , X22), en la segunda aparece la materia, en la tercera el día, en la"))
        self.label_53.setText(_translate("MainWindow", "cuarta el horario y en la quinta el profesor asignado (en dado caso de tener uno, si no aparecerá como \"Sin asignar\")."))
        self.label_54.setText(_translate("MainWindow", "Esta tabla al ser tan grande, cuenta en su lado derecho con una barra de desplazamiento, para una facilitar la navegación."))
        self.label_55.setText(_translate("MainWindow", "Horario por Salón"))
        self.label_56.setText(_translate("MainWindow", "En esta otra pestaña, se despliegará de igual manera en forma de tabla, el horario de únicamente una Aula de todo el edificio X."))
        self.label_57.setText(_translate("MainWindow", "Las diferencia más notables, es que ahora se tiene una barra seleccionadora abajo del título de la pestaña, en la que vas"))
        self.label_58.setText(_translate("MainWindow", "a poder elegir de cuál aula quieres visualizar su horario (X1, X2, X3, X4, ... ,X22). Eliminando así la columna de la tabla"))
        self.label_59.setText(_translate("MainWindow", "donde se mostraban las aulas, ya que ahora no es necesario, puesto que aparecerá arriba en la barra de selección."))
        self.label_60.setText(_translate("MainWindow", "Por comodidad, en esta pestaña se adapto el tamaño para que toda la tabla sea visible, sin necesidad de usar una barra de desplazamiento."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Consultar Horario"))
        self.label_20.setText(_translate("MainWindow", "Función"))
        self.label_21.setText(_translate("MainWindow", "AÑADIR PROFESOR"))
        self.label_61.setText(_translate("MainWindow", "El programa Genera horarios en todas las aulas del edificio X de manera automática,"))
        self.label_62.setText(_translate("MainWindow", "pero los profesores tienen que ser ingresados de manera manual, tomando en cuenta el horario generado."))
        self.label_63.setText(_translate("MainWindow", "ERROR: Si haces click en \"AÑADIR\" sin haber llenado todos los campos primero, saltará un mensaje de error"))
        self.label_64.setText(_translate("MainWindow", "Al hacer click en esta función dentro del menu principal, aparecerá una ventana en la que se te solicitarán 3 campos"))
        self.label_65.setText(_translate("MainWindow", "Nombre del profesor"))
        self.label_66.setText(_translate("MainWindow", "ERROR: Si pones el nombre de una matería inexistente dentro del salón seleccionado, saltará un mensaje de error"))
        self.label_67.setText(_translate("MainWindow", "Aquí va a poner el nombre del profesor que deseas agregar a la sección que especifique a continuación"))
        self.label_68.setText(_translate("MainWindow", "Nombre del salón"))
        self.label_69.setText(_translate("MainWindow", "Aquí aparecerá una barra despliegable, en el que podrá seleccionar el aula al que desea asignar al profesor"))
        self.label_70.setText(_translate("MainWindow", "Nombre de la materia"))
        self.label_71.setText(_translate("MainWindow", "Aquí aparecerá una barra despliegable, en el que podrá seleccionar la materia que se le quiere asignar al profesor"))
        self.label_72.setText(_translate("MainWindow", "en base al aula seleccionada con anterioridad."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Añadir Profesor"))
        self.label_22.setText(_translate("MainWindow", "Función"))
        self.label_23.setText(_translate("MainWindow", "EDITAR MATERIAS"))
        self.label_47.setText(_translate("MainWindow", "NOTA // LE RECOMENDAMOS LEER LA PESTAÑA \"GENERAR HORARIOS\" EN DADO CASO DE NO TENER NINGUNA MATERIA DESPLIEGADA EN ESTA FUNCIÓN"))
        self.label_73.setText(_translate("MainWindow", "Al hacer click en esta función dentro del menu principal, aparecerá una ventana en la que se te solicitarán 4 campos,"))
        self.label_74.setText(_translate("MainWindow", "y tendrás un recuadro en medio de ellos, el cuál es en realidad una lista."))
        self.label_75.setText(_translate("MainWindow", "Nombre del Salón"))
        self.label_76.setText(_translate("MainWindow", "Barra despliegable donde seleccionarás el número de aula donde quieres realizar la modificación de la materia"))
        self.label_77.setText(_translate("MainWindow", "Día de la Clase"))
        self.label_78.setText(_translate("MainWindow", "Barra despliegable donde seleccionarás el día de la clase donde quieres realizar la modificación de la materia"))
        self.label_79.setText(_translate("MainWindow", "Recuadro (Lista)"))
        self.label_80.setText(_translate("MainWindow", "Una vez teniendo seleccionadas ambas opciones de arriba, se despliegará el listado de materias disponibles"))
        self.label_81.setText(_translate("MainWindow", "de acuerdo a los dos parámetros previamente establecidos"))
        self.label_82.setText(_translate("MainWindow", "Seleccione la Materia que desee editar"))
        self.label_83.setText(_translate("MainWindow", "Este listado se actualizará al igual que el recuadro de arriba, dependiendo de los dos parámetros establecidos con"))
        self.label_84.setText(_translate("MainWindow", "anterioridad. Aquí podrás seleccionar la materia que deseas editar."))
        self.label_85.setText(_translate("MainWindow", "Opciones de Edición"))
        self.label_86.setText(_translate("MainWindow", "Aquí habrá 3 opciones de edición, dependiendo de lo que escojas, se abrirá una nueva ventana para recolectar los campos"))
        self.label_87.setText(_translate("MainWindow", "y hacer la edición deseada en el horario."))
        self.label_88.setText(_translate("MainWindow", "Editar Horario"))
        self.label_89.setText(_translate("MainWindow", "Editar Nombre de la Materia"))
        self.label_90.setText(_translate("MainWindow", "Eliminar Materia"))
        self.label_91.setText(_translate("MainWindow", "Se te va a pedir la Hora de Inicio y de Fin"))
        self.label_92.setText(_translate("MainWindow", "Ejemplo // Inicio: 11   Fin: 13"))
        self.label_93.setText(_translate("MainWindow", "Se va a eliminar la materia seleccionada"))
        self.label_94.setText(_translate("MainWindow", "Se te va a pedir el nuevo nombre de la materia"))
        self.label_95.setText(_translate("MainWindow", "en un campo en blanco"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Editar Materias"))
        self.label_25.setText(_translate("MainWindow", "CRÉDITOS"))
        self.label_24.setText(_translate("MainWindow", "Equipo de desarrollo los BichoLovers"))
        self.label_27.setText(_translate("MainWindow", "MALDONADO MELENDEZ DIEGO ALBERTO"))
        self.label_28.setText(_translate("MainWindow", "CAMPOS ORNELAS OSCAR"))
        self.label_29.setText(_translate("MainWindow", "ARELLANO CERVANTES GUILLERMO ANTONIO"))
        self.label_30.setText(_translate("MainWindow", "SÁNCHEZ SÁNCHEZ JAIME IVÁN"))
        self.label_31.setText(_translate("MainWindow", "En el Rol de Admin:"))
        self.label_32.setText(_translate("MainWindow", "Como desarrollador del Backend:"))
        self.label_33.setText(_translate("MainWindow", "En el rol de Tester:"))
        self.label_34.setText(_translate("MainWindow", "Como desarrollador del Frontend:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Créditos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
